### ISSUE TITLE
Not allowing other machines to connect to the local machine via port 80 and 443 but allowing the local machine to connect to the internet web servers?

### ISSUE THREAD

**Issue by samiux** [CoolerVoid/HiddenWall#5]
HiddenWall is not working properly on a machine that is not a web server as port 80 and 443 are required to connected in order to access internet servers for files downloading.  However, port 80 and 443 are not using in that machine.  If they are opened on the machine, the attacker can use those ports to make a shell connection.  Is it possible to allow the machine to connect to the outside world's web servers but not allow others to connect the machine via port 80 and 443?

**Comment by CoolerVoid** [comment]
That is not true, I use HiddenWall on my Desktop machine, so you need to write your custom rule in YAML file to liberate it for your purpose, just for example:
$ cat rules/server.yaml
````yaml
module_name: SandWall
public_ports: 80,443,53
unhide_key: AbraKadabra
hide_key: Shazam
fake_device_name: usb14
liberate_in_2_out: False
whitelist: 
- machine: 
   ip: 192.168.100.181
   open_ports: 22,21
- machine:
   ip: 192.168.100.22
   open_ports: 22 
```
Look to the yaml's field "liberate_in_2_out" if set "true" The machine is open to connecting to other external machines following the rule "in to out". Anyway, the default rule is to block all communication. To liberate you need to set the value in the field "public_ports" or in the proper whitelist field the IP.

Do you have another question? so I am glad to help at any point.

**Comment by samiux** [comment]
Does the following message caused the matter?

```
Skipping BTF generation for /home/samiux/HiddenWall/module_generator/output/SandWall.ko due to unavailability of vmlinux
```

**Comment by samiux** [comment]
Case #1 : When rules/serveer.yaml is set as the following, I can surf the internet.  However, I run ```sudo python3 -m http.server 80``` on my desktop, the port 80 can be access also.  It doesn't matter whether ```liberate_in_2_out``` is true or false.  It is not as my expected.

```
module_name: SandWall
public_ports: 80,443,53
unhide_key: AbraKadabra
hide_key: Shazam
fake_device_name: usb14
liberate_in_2_out: True
whitelist: 
- machine: 
   ip: 192.168.100.181
   open_ports: 22,21
- machine:
   ip: 192.168.100.22
   open_ports: 22
```

Case #2 : When rules/serveer.yaml is set as the following, I cannot surf the internet.  Meanwhile, I run ```sudo python3 -m http.server 80``` on my desktop, the port 80 cannot be access also.  It doesn't matter whether ```liberate_in_2_out``` is true or false.

```
module_name: SandWall
public_ports: 53
unhide_key: AbraKadabra
hide_key: Shazam
fake_device_name: usb14
liberate_in_2_out: True
whitelist: 
- machine: 
   ip: 192.168.100.181
   open_ports: 22,21
- machine:
   ip: 192.168.100.22
   open_ports: 22
```
